---
auth_methods:
  basic:
    params:
      username: "username"
      password: "password"
proxies:
  - "http://my-http-proxy:8080/"
  - "https//my-https-proxy:8443/"
targets:
  - url: "https://www.example.com/"
